import type { Question } from "@/types";

export const surveyQuestions: Question[] = [
  {
    id: 1,
    type: "single",
    question: "How often do you consume caffeine?",
    subtitle: "Think about all sources — coffee, tea, energy drinks, etc.",
    options: [
      "Multiple times a day",
      "Once a day",
      "2–3 times a week",
      "Once a week or less",
      "Never",
    ],
  },
  {
    id: 2,
    type: "single",
    question: "What is your primary source of caffeine?",
    subtitle: "Choose the one you rely on most.",
    options: [
      "Coffee",
      "Tea",
      "Energy drinks",
      "Soft drinks / Soda",
      "Pre-workout supplements",
      "Caffeine pills",
      "Other",
    ],
  },
  {
    id: 3,
    type: "single",
    question: "When do you typically consume caffeine?",
    subtitle: "Pick the time window that fits you best.",
    options: [
      "Early morning (before 8 am)",
      "Morning (8 am – 12 pm)",
      "Afternoon (12 pm – 5 pm)",
      "Evening (5 pm – 9 pm)",
      "Late night (after 9 pm)",
    ],
  },
  {
    id: 4,
    type: "multiple",
    question: "Why do you consume caffeine?",
    subtitle: "Select all that apply.",
    options: [
      "Boost energy levels",
      "Improve focus & concentration",
      "Social habit",
      "Enjoy the taste",
      "Combat fatigue / drowsiness",
      "Improve mood",
      "Athletic or physical performance",
      "Reduce headaches",
    ],
  },
  {
    id: 5,
    type: "likert",
    question: "Caffeine significantly improves my productivity.",
    subtitle: "Rate how strongly you agree or disagree.",
    minLabel: "Strongly Disagree",
    maxLabel: "Strongly Agree",
    min: 1,
    max: 5,
  },
  {
    id: 6,
    type: "multiple",
    question: "Which side effects have you experienced from caffeine?",
    subtitle: "Select all that apply.",
    options: [
      "Jitteriness / shakiness",
      "Increased heart rate",
      "Sleep disruption / insomnia",
      "Anxiety or nervousness",
      "Headaches (when not consumed)",
      "Improved alertness (positive)",
      "Digestive issues",
      "None — no side effects",
    ],
  },
  {
    id: 7,
    type: "select",
    question: "On average, how many hours of sleep do you get per night?",
    subtitle: "Honest answers help us spot patterns.",
    options: [
      "Less than 4 hours",
      "4–5 hours",
      "5–6 hours",
      "6–7 hours",
      "7–8 hours",
      "More than 8 hours",
    ],
  },
  {
    id: 8,
    type: "single",
    question: "Do you increase caffeine intake during exams or high-stress periods?",
    subtitle: "Think about the last time you were under heavy pressure.",
    options: [
      "Yes, significantly more",
      "Yes, slightly more",
      "No change",
      "I actually reduce it",
      "Not applicable",
    ],
  },
  {
    id: 9,
    type: "likert",
    question: "I feel dependent on caffeine to function normally.",
    subtitle: "Be honest — there are no wrong answers.",
    minLabel: "Strongly Disagree",
    maxLabel: "Strongly Agree",
    min: 1,
    max: 5,
  },
];

export const TOTAL_QUESTIONS = surveyQuestions.length;
